version: '3.8'
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    volumes:
      - loki-data:/loki  # optional persistence
    networks:
      - observability

  tempo:
      image: grafana/tempo:latest
      ports:
        - "3200:3200"   # Tempo HTTP API
        - "43170:4317"   # OTLP gRPC
        - "43180:4318"   # OTLP HTTP
      volumes:
        - tempo-data:/var/tempo
        - ./tempo.yaml:/etc/tempo.yaml:ro,Z
      command: ["--config.file=/etc/tempo.yaml"]
      restart: unless-stopped
      networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"   # Alloy Web-UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "9464:9464"     # Prometheus scrape endpoint exposed by Alloy exporter
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro,Z
      - alloy-data:/var/lib/alloy/data
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
      - tempo
    restart: unless-stopped
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    depends_on:
      - loki
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.enable-lifecycle --web.enable-remote-write-receiver
    depends_on:
      - alloy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - observability

volumes:
  prometheus-data:
  grafana-data:
  alloy-data:
  loki-data:
  tempo-data:

networks:
  observability:
    driver: bridge